[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild" # Ensures efficient bundling for Node.js functions

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
